name: 'bookstore-microservice-app'
services:
  catalog-service:
    image: minh1010/bookstore-catalog-service
    container_name: catalog-service
    env_file:
      - ../../.env
    ports:
      - "8081:8081"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 700m

  order-service:
    image: minh1010/bookstore-order-service
    container_name: order-service
    env_file:
      - ../../.env
    environment:
      - RABBITMQ_HOST=bookstore-rabbitmq
    ports:
      - "8082:8082"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 700m

  notification-service:
    image: minh1010/bookstore-notification-service
    container_name: notification-service
    env_file:
      - ../../.env
    environment:
      - RABBITMQ_HOST=bookstore-rabbitmq
      - MAIL_HOST=mailhog
    ports:
      - "8083:8083"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 700m

  api-gateway:
    image: minh1010/bookstore-api-gateway
    container_name: api-gateway
    env_file:
      - ../../.env
    ports:
      - "8989:8989"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 700m

  web--app:
    image: minh1010/bookstore-webapp
    container_name: web-app
    env_file:
      - ../../.env
#    environment:
#      - OAUTH2_SERVER_URL=http://keycloak:9191
#      - MANAGEMENT_TRACING_ENABLED=${MANAGEMENT_TRACING_ENABLED}
#      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://tempo:9411
    ports:
      - "8080:8080"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 700m
