name: 'bookstore-microservice'
services:
  catalog-service:
    image: minh1010/bookstore-catalog-service
    container_name: catalog-service
    env_file:
      - ../../.env
    ports:
      - "8081:8081"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 700m

  order-service:
    image: minh1010/bookstore-order-service
    container_name: order-service
    env_file:
      - ../../.env
    environment:
      - RABBITMQ_HOST=bookstore-rabbitmq
    ports:
      - "8082:8082"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 700m
