version: "3.8"
name: "spring-boot-microservices-catalog"

services:
  catalog-service:
    build: .
    container_name: catalog-service
    ports:
      - "8080:8080"
    env_file:
      - ../../.env
    deploy:
      resources:
        limits:
          memory: 600m

