version: "3.8"
name: "spring-boot-microservices-catalog"

services:
  catalog-service:
    build: .
    container_name: catalog-service
    ports:
      - "8081:8081"
    env_file:
      - ../../catalog-service/.env
    deploy:
      resources:
        limits:
          memory: 600m

