name: 'bookstore-microservice-app'
services:
  catalog-service:
    image: minh1010/bookstore-catalog-service
    container_name: catalog-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SWAGGER_API_GATEWAY_URL=http://api-gateway:8989/catalog
      - MANAGEMENT_TRACING_ENABLED=${MANAGEMENT_TRACING_ENABLED}
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://tempo:9411
    env_file:
      - ./docker-compose.env
    networks:
      - bookstore-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 700m

  order-service:
    image: minh1010/bookstore-order-service
    container_name: order-service
    env_file:
      - ./docker-compose.env
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - ORDERS_CATALOG_SERVICE_URL=http://api-gateway:8989/catalog
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - OAUTH2_SERVER_URL=http://keycloak:9191
      - SWAGGER_API_GATEWAY_URL=http://api-gateway:8989/orders
      - MANAGEMENT_TRACING_ENABLED=${MANAGEMENT_TRACING_ENABLED}
      - RABBITMQ_HOST=bookstore-rabbitmq
    ports:
      - "8082:8082"
    networks:
      - bookstore-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 700m

  notification-service:
    image: minh1010/bookstore-notification-service
    container_name: notification-service
    env_file:
      - ./docker-compose.env
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - RABBITMQ_HOST=bookstore-rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - MAIL_HOST=mailhog
      - MAIL_PORT=1025
      - MANAGEMENT_TRACING_ENABLED=${MANAGEMENT_TRACING_ENABLED}
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://tempo:9411
    ports:
      - "8083:8083"
    networks:
      - bookstore-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 700m

  api-gateway:
    image: minh1010/bookstore-api-gateway
    container_name: api-gateway
    env_file:
      - ./docker-compose.env
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - CATALOG_SERVICE_URL=http://catalog-service:8081
      - ORDER_SERVICE_URL=http://order-service:8082
      - MANAGEMENT_TRACING_ENABLED=${MANAGEMENT_TRACING_ENABLED}
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://tempo:9411
    ports:
      - "8989:8989"
    networks:
      - bookstore-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 700m

  web--app:
    image: minh1010/bookstore-web-app
    container_name: web-app
    env_file:
      - ./docker-compose.env
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - BOOKSTORE_API_GATEWAY_URL=http://api-gateway:8989
      - OAUTH2_SERVER_URL=http://keycloak:9191
      - MANAGEMENT_TRACING_ENABLED=${MANAGEMENT_TRACING_ENABLED}
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://tempo:9411
    ports:
      - "8080:8080"
    networks:
      - bookstore-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 700m

networks:
  bookstore-network:
    external: true
